export const GET_WORKSPACE_URL_BEGIN = "GET_WORKSPACE_URL_BEGIN";
export const GET_WORKSPACE_URL_SUCCESS = "GET_WORKSPACE_URL_SUCCESS";

export const SIGNIN_BEGIN = "SIGNIN_BEGIN";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";

export const ERROR = "ERROR";
export const ERROR_HIDE = "ERROR_HIDE";
